project:
  type: website
  output-dir: _site  # ou docs, selon ton choix
website:
  title: "Miam miam les mathématiques"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    sidebar:
    style: "docked"
    search: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introduction"
        href: index.qmd
      - section: "Rappels ?"
        href: rappels/basics-summary.qmd
        contents:
          - text: "Proportions" 
            href: rappels/basics-proportion.qmd
          - text: "Puissances"
            href: rappels/basics-power.qmd
      - section: "Théorie des probabilités"
        href: proba/proba-summary.qmd
        contents:
          - text: "Cadre mathématique" 
            href: proba/proba-framework.qmd
          - text: "Variables aléatoires"
            href: proba/proba-rand_var.qmd
format:
  html:
    theme: sketchy
    css: 
      - styles.css
      - custom.css
    js: script.js
    includes:
      in_header: 
        - <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    toc: true
editor: visual
callout-appearance: default
execute: 
  echo: false
  cache: true
  message: false
  warning: false
# Important : inclure le script R
  code-overrides:
    include-before: setup.R
  
