---
title: "Puissances entières et rationnelles" 
---

# Introduction

L'exponentielle et le logarithme sont deux fonctions indispensables pour un scientifique. Afin de mieux comprendre en quoi elles le sont, il faut maîtriser les calculs sur les puissances mais surtout leur sens.

# Puissances entières naturelles

C'est la situation initiale, où la définition est limpide.

::: {.alert .alert-warning}
> Définition : soit $n$ un entier naturel non-nul, et $a$ un nombre réel, alors le nombre réel $a^n$ est défini comme le produit de $n$ facteurs tous égaux à $a$ :
>
> $$
> a^n = \underbrace{a\times a\times\dots\times a\times a}_{n\textrm{ fois}}
> $$
:::

Par exemple, le carré et le cube assez classiques

$$
\begin{array}{lllll}
3^2 = 3\times 3 =9\\
\pi^3 = \pi\times\pi\times\pi \simeq 31,006
\end{array}
$$

Cette représentation de la puissance ne fonctionne que pour des entiers naturels non-nuls ! De là, on déduit les \*\*règles de calculs sur les puissances\*\*.

::: {.alert .alert-warning}
> Propriété : soit $n,m\in\mathbb N^*$, et $a,b\in\mathbb R$, alors $$\begin{array}{l}a^na^m&=a^{n+m}\\(a^n)^m &= a^{nm}\\a^nb^n&=(ab)^n\end{array}$$
:::

::: {.callout-tip collapse="true" title="Démonstration"}
-   pour le premier résultat

    $$\begin{array}{l}
    a^na^m&=\underbrace{a\times a\times\dots\times a\times a}_{n\textrm{ fois}}\times\underbrace{a\times a\times\dots\times a\times a}_{m\textrm{ fois}}\\
    &=\underbrace{a\times a\times\dots\times a\times a\times a\times a\times\dots\times a\times a}_{n+m\textrm{ fois}}\\
    &=a^{n+m},
    \end{array}
    $$

-   pour le second $$\begin{array}{l} 
    (a^n)^m&=\underbrace{a^n\times a^n\times\dots\times a^n\times a^n}_{m\textrm{ fois}} \\ 
    &= \underbrace{\underbrace{a\times a\times\dots\times a\times a}_{n\textrm{ fois}}\times \dots \times \underbrace{a\times a\times\dots\times a\times a}_{n\textrm{ fois}}}_{m \textrm{ fois}}\\
    &= a^{nm}\end{array},$$

-   enfin, pour le dernier on réordonne les facteurs $$ \begin{array}{l}a^nb^n&=\underbrace{a\times a\times\dots\times a}_{n\textrm{ fois}}\times \underbrace{b\times b\times\dots\times b}_{n\textrm{ fois}}\\&=\underbrace{(a\times b)\times (a\times b)\times\dots\times(a\times b)}_{n\textrm{ fois}}&=(ab)^n.\end{array}$$
:::

Ces règles sont **fondamentales** pour comprendre comment les autres types de puissances sont définis. Jusqu'à l'exponentielle, l'obsession consiste à garantir que chaque choix de définition permet de rester **compatible** avec ces règles de calculs :

-   le produit de deux puissances d'un même nombre est égal à la puissance de ce même nombre où l'exposant est obtenu en additionnant les deux exposants

-   la puissance d'une puissance d'un nombre donné est égal à la puissance de ce même nombre où l'exposant est obtenu en multipliant les deux exposants

Cela signifie évidemment qu'il n'y a pas réellement de nouvelles formules à part les définitions.

# Puissances entières relatives

Ici, on cherche à étendre la notion de puissance, au sens où les règles de calculs restent valides. Tout repose sur l'écriture de **l'inverse** d'un nombre $$a^{-1}=\frac1a.$$ En effet, partant du constat que si $m\geq n$, $$\begin{array}{l}
\displaystyle\frac{a^n}{a^n}=1\\
\displaystyle\frac{a^m}{a^n}=\frac{\overbrace{a\times a\times\dots\times a}^{n\textrm{ fois}}\times \overbrace{a\times a\times\dots\times a}^{m-n\textrm{ fois}}}{\underbrace{a\times a\times\dots\times a}_{n \textrm{ fois}}}= \overbrace{a\times a\times\dots\times a}^{m-n\textrm{ fois}} = a^{m-n}\\
\displaystyle\frac{a^n}{a^m}=\frac{\overbrace{a\times a\times\dots\times a}^{n \textrm{ fois}}}{\underbrace{a\times a\times\dots\times a}_{n\textrm{ fois}}\times \underbrace{a\times a\times\dots\times a}_{m-n\textrm{ fois}}}= \frac{1}{\underbrace{a\times a\times\dots\times a}_{m-n\textrm{ fois}}} =\frac{1}{ a^{m-n}}
\end{array}$$

Ainsi, le bon choix à faire est le suivant : ::: {.alert .alert-warning } \> Définition : pour $n\in\mathbb Z^*,$ le nombre $a^{-n}$ est **l'inverse** de $a^n$, par convention, on pose $a^0=1.$ Ainsi pour $a\in\mathbb R^*$ et $m,n\in\mathbb Z$ $$\begin{array}{l}a^{-n}= \frac{1}{a^n}= \left(\frac{1}{a}\right)^n=(a^{-1})^n\\\displaystyle \frac{a^m}{a^n}=a^{m-n}=\frac{1}{a^{n-m}}\end{array}$$

:::

L'information primordiale à retenir, c'est ce lien entre puissance négative et inverse de la puissance positive. Par exemple : $$\begin{array}{l}\displaystyle\, 2^{-3}&=\frac{1}{2^3}=\frac{1}{8}\\\frac{6^7}{3^94^2}&=\frac{2^73^7}{2^43^9}=2^{3}3^{-2}= \frac{8}{9}\end{array}$$

# Puissances rationnelles

Toujours dans la même obsession, le choix retenu pour les puissances rationnelles doit rester compatible avec les règles de calcul. Prenons l'exemple de la puissance $\tfrac12$, Souvent on retient que cela correspond à la racine carrée, c'est important de se souvenir pourquoi.

Pour rappel,

::: {.alert .alert-warning}
> Définition : pour tout réel positif $a$, le nombre $\sqrt a$ est l'**unique réel positif** qui élevé au carré donne $a$ $$\sqrt{a}^2=a$$
:::

Cette définition est à mettre en lien avec la courbe de la fonction carrée
```{r}

```






# Pour s'entraîner

::: spaced-list
1.  Calculer : $3^4$
2.  Calculer : $5^2 \times 5^3$
3.  Calculer : $(2^3)^2$
4.  Calculer : $\left( \frac{4^2}{2^3} \right)^2$
5.  Calculer : $7^1 \times 7^2 \times 7^3$
6.  Calculer : $2^{-3}$
7.  Calculer : $5^{-1} \times 5^4$
8.  Calculer : $\left( \frac{3}{4} \right)^{-2}$
9.  Calculer : $\left(2^{-2}\right)^3$
10. Calculer : $10^0 + 10^{-1}$
11. Calculer : $9^{1/2}$
12. Calculer : $27^{1/3}$
13. Calculer : $16^{3/4}$
14. Calculer : $\left( \frac{1}{8} \right)^{2/3}$
15. Calculer : $81^{-1/2}$
16. Simplifier : $x^3 \cdot x^4$
17. Simplifier : $\dfrac{a^5}{a^2}$
18. Simplifier : $(b^{-2})^3$
19. Simplifier : $\left( \dfrac{c^3}{c^{-1}} \right)^2$
20. Simplifier : $(d^{1/2} \cdot d^{1/3})$
21. Simplifier : $\left( \dfrac{1}{e^{2/5}} \right)^3$
22. Simplifier : $(f^{-1})^{3/2}$
:::

On pourra également consulter les sources suivantes : - <https://fr.khanacademy.org/math/algebra-basics/alg-basics-expressions-with-exponents> - <https://fr.khanacademy.org/math/3eme-annee-secondaire/xd903d14ae2b1276e:algebre-puissances-et-racines/xd903d14ae2b1276e:hors-programme-une-racine-est-une-puissance-a-exposant-fractionnaire/v/rewriting-roots-as-rational-exponents>
